version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: gavl-db
    environment:
      POSTGRES_USER: ${DB_USER:-gavl}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_change_me}
      POSTGRES_DB: ${DB_NAME:-gavl_predictions}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-gavl}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # TheGAVL API
  gavl-api:
    build: .
    container_name: gavl-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-gavl}:${DB_PASSWORD:-secure_password_change_me}@postgres:5432/${DB_NAME:-gavl_predictions}
      API_KEY: ${API_KEY:-change-me-in-production}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: gavl-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

volumes:
  postgres_data:
  prometheus_data:

networks:
  default:
    name: gavl-network
